name: Playwright Tests
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.57.0-jammy
    strategy:
      fail-fast: false
      matrix:
        suite:
          - name: "API Tests"
            path: "tests/APIs/"
          - name: "UI Tests"
            path: "tests/UItests/"
    name: ${{ matrix.suite.name }}
    steps:
      - uses: actions/checkout@v4
      - name: Run ${{ matrix.suite.name }}
        run: |
          pip install -r requirements.txt
          pytest ${{ matrix.suite.path }} --headless=true
